# Jekyll Primer theme _custom.yml
# https://github.com/pages-themes/primer/blob/master/_config.yml

title: APLS Documentation

baseurl: /APLS
plugins:
  - jekyll-relative-links

exclude:
  - node_modules
  - script

sass:
  style: :compressed

# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.5.4

github:
  private: false
  license:
    name: CC BY-NC-SA 4.0
  source:
    branch: "main"
    path: "/"
  repository_url: https://github.com/djvill/APLS

lang: en-US

########################################
#### Config for just-the-docs theme ####
########################################

##Favicon
favicon_ico: /assets/img/1f34e.svg

##Aux links
##Config: https://just-the-docs.github.io/just-the-docs/docs/configuration/#aux-links
aux_links:
  "View on GitHub":
    - "//github.com/djvill/APLS"
aux_links_new_tab: true

##Callouts (e.g., "Note", "Warning")
##Use: https://just-the-docs.github.io/just-the-docs/docs/ui-components/callouts/
##Config: https://just-the-docs.github.io/just-the-docs/docs/configuration/#callouts
callouts:
  note:
    title: Note
    color: yellow
    icon: assets/img/fa-circle-info.png  # Not implemented yet. Need to use JS to inject icon into .note::before

##Google Analytics
ga_tracking: G-TT6NWBCLVW 
ga_tracking_anonymize_ip: true  # Use GDPR compliant Google Analytics settings
